// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/adr.proto

package adr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ADRService_AnalyzeADR_FullMethodName = "/proto.ADRService/AnalyzeADR"
)

// ADRServiceClient is the client API for ADRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ADRServiceClient interface {
	AnalyzeADR(ctx context.Context, in *ADRRequest, opts ...grpc.CallOption) (*ADRResponse, error)
}

type aDRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewADRServiceClient(cc grpc.ClientConnInterface) ADRServiceClient {
	return &aDRServiceClient{cc}
}

func (c *aDRServiceClient) AnalyzeADR(ctx context.Context, in *ADRRequest, opts ...grpc.CallOption) (*ADRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ADRResponse)
	err := c.cc.Invoke(ctx, ADRService_AnalyzeADR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ADRServiceServer is the server API for ADRService service.
// All implementations must embed UnimplementedADRServiceServer
// for forward compatibility.
type ADRServiceServer interface {
	AnalyzeADR(context.Context, *ADRRequest) (*ADRResponse, error)
	mustEmbedUnimplementedADRServiceServer()
}

// UnimplementedADRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedADRServiceServer struct{}

func (UnimplementedADRServiceServer) AnalyzeADR(context.Context, *ADRRequest) (*ADRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeADR not implemented")
}
func (UnimplementedADRServiceServer) mustEmbedUnimplementedADRServiceServer() {}
func (UnimplementedADRServiceServer) testEmbeddedByValue()                    {}

// UnsafeADRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ADRServiceServer will
// result in compilation errors.
type UnsafeADRServiceServer interface {
	mustEmbedUnimplementedADRServiceServer()
}

func RegisterADRServiceServer(s grpc.ServiceRegistrar, srv ADRServiceServer) {
	// If the following call pancis, it indicates UnimplementedADRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ADRService_ServiceDesc, srv)
}

func _ADRService_AnalyzeADR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ADRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADRServiceServer).AnalyzeADR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ADRService_AnalyzeADR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADRServiceServer).AnalyzeADR(ctx, req.(*ADRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ADRService_ServiceDesc is the grpc.ServiceDesc for ADRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ADRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ADRService",
	HandlerType: (*ADRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeADR",
			Handler:    _ADRService_AnalyzeADR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adr.proto",
}
